CREATE SEQUENCE seq_item_id      START WITH 10000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_bom_line_id  START WITH 1      INCREMENT BY 1 CACHE 50 NOCYCLE;
CREATE SEQUENCE seq_inv_txn_id   START WITH 800000 INCREMENT BY 1 CACHE 100 NOCYCLE;
CREATE SEQUENCE seq_error_log_id START WITH 1      INCREMENT BY 1 CACHE 50 NOCYCLE;
